name: Translation status
on:
  push:
    branches:
      - i18n-gitlocalize

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm ci

      - name: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
          for removed_file in ${removed_files[@]}; do
            echo "Do something with this ${removed_file}."
          done


      - name: Translated
        run: npm run translated


