name: Translation status
on:
  push:
    branches:
      - i18n-gitlocalize

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm ci

      - name: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: translated
        run: npm run translated -- "${{ steps.files.outputs.all }}"

